[package]
authors = ["Cytosine2020", "victoryang00"]
edition = "2021"
name = "MVVM"
version = "0.1.0"

[dependencies]
wasm-bindgen = "0.2"
wasm-bindgen-test = "0.3.30"
wasmtime-jit="0.36.0"
[lib]
crate-type = ["cdylib", "rlib"]
