name: build-ubuntu

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        build: [Debug, Release]
        standard: [cxx23]

    defaults:
      run:
        shell: bash

    name: "${{matrix.standard}}-${{matrix.build}}"
    steps:
    - uses: actions/checkout@v2

    - name: Install Dependency
      run: sudo apt install libssl-dev gcc-13 g++-13 libprotobuf-c-dev libprotobuf-dev libgrpc-dev libfmt-dev llvm-14-dev libedit-dev libcxxopts-dev libpfm4-dev liblldb-dev libbenchmark-dev ninja-build libpcap-dev libopenblas-pthread-dev
      
    - name: Checkout
      run: |
        git submodule update --init --recursive

    - name: Install WASI SDK
      run: |
        cd /opt
        sudo wget http://108.181.27.85/wasi/wasi-sdk-21.0-linux.tar.gz
        sudo tar -xzf wasi-sdk-*.tar.gz
        mv wasi-sdk-21 wasi-sdk
        
    - name: Make WASI Socket Ext
      run: |
        cd lib/wasm-micro-runtime/samples/socket-api/
        cmake . -DCMAKE_C_COMPILER_WORK=1 -DCMAKE_CXX_COMPILER_WORK=1
        make -j

    - name: Install AOT wamrc
      run: |
        cd lib/wasm-micro-runtime/wamr-compiler
        mkdir build
        cd build
        cmake .. -DWAMR_BUILD_AOT=1 -DWAMR_BUILD_AOT_STACK_FRAME=1 -DWAMR_BUILD_DEBUG_AOT=0 -DWAMR_BUILD_DUMP_CALL_STACK=1 -DWAMR_BUILD_CUSTOM_NAME_SECTION=1 -DWAMR_BUILD_SHARED_MEMORY=1 -DWAMR_BUILD_WITH_CUSTOM_LLVM=1 -DWAMR_BUILD_LOAD_CUSTOM_SECTION=1 -DLLVM_DIR=/usr/lib/llvm-14/lib/cmake/llvm/
        make -j

    - name: configure cmake
      run: sudo touch /usr/lib/llvm-14/lib/libMLIRSupportIndentedOstream.a && CC=gcc-13 CXX=g++-13 cmake -S $GITHUB_WORKSPACE -B ${{runner.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.build}} -DLLVM_DIR=/usr/lib/llvm-14/lib/cmake/llvm/

    - name: build
      working-directory: ${{runner.workspace}}/build
      run: cmake --build . --config ${{matrix.build}}
      