name: build-ubuntu

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        build: [Debug, Release]
        standard: [cxx23]

    defaults:
      run:
        shell: bash

    name: "${{matrix.standard}}-${{matrix.build}}"
    steps:
    - uses: actions/checkout@v2

    - name: Install Dependency
      run: sudo apt install libssl-dev libprotobuf-c-dev libprotobuf-dev libgrpc-dev libfmt-dev llvm-14-dev libedit-dev libcxxopts-dev libpfm4-dev

    - name: Install WASI SDK
      run: |
        cd /opt
        sudo wget https://github.com/WebAssembly/wasi-sdk/releases/download/wasi-sdk-20/wasi-sdk-20.0-linux.tar.gz
        sudo tar -xzf wasi-sdk-*.tar.gz
        sudo mv wasi-sdk-20.0 wasi-sdk

    - name: Checkout
      run: git submodule update --init

    - name: configure cmake
      run: sudo touch /usr/lib/llvm-14/lib/libMLIRSupportIndentedOstream.a && cmake -S $GITHUB_WORKSPACE -B ${{runner.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.build}} -DLLVM_DIR=/usr/lib/llvm-14/lib/cmake/llvm/

    - name: build
      working-directory: ${{runner.workspace}}/build
      run: cmake --build . --config ${{matrix.build}}

    - name: test
      working-directory: ${{runner.workspace}}/build
      run: ctest -V