name: Main Checks

on:
  pull_request:
  push:
    branches: [main]

jobs:
  integration_tests:
    name: Integration Tests on ${{ matrix.toolchain }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        toolchain:
          # anyway to dynamically grep the MSRV from Cargo.toml?
          - 1.56.0 # MSRV
          - stable

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          target: wasm32-unknown-unknown
          override: true
          profile: minimal

      - uses: jetli/wasm-pack-action@v0.3.0
        with:
          version: "latest"

      - uses: Swatinem/rust-cache@v1


      - name: Run tests - mvvm
        run: |
          wasm-pack test --chrome --firefox --headless

  unit_tests:
    name: Unit Tests on ${{ matrix.toolchain }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          # anyway to dynamically grep the MSRV from Cargo.toml?
          - 1.56.0 # MSRV
          - stable
          - nightly

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          override: true
          profile: minimal

      - uses: Swatinem/rust-cache@v1

      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-targets --workspace
